# Matrices, Linear Systems, and Transformations
A matrix is more than a rectangle of numbers. It can describe a linear transformation, a dataset, a system of equations, or a layer of learned parameters. Seeing those meanings together is what makes matrix operations start to feel natural.

If vectors are the language of single points or directions, matrices are the language of structured transformations and collections. Many ML operations become compact and efficient when written in matrix form.

In [1]:
import numpy as np

A = np.array([[2.0, 1.0], [1.0, 3.0]])
x = np.array([4.0, 5.0])
print('A:\n', A)
print('x:', x)
print('Ax:', A @ x)

A:
 [[2. 1.]
 [1. 3.]]
x: [4. 5.]
Ax: [13. 19.]


One way to read Ax is as a transformation applied to a vector. Another is as a weighted combination of the matrix columns. Both interpretations are useful, and both lead to the same numbers.

In [2]:
b = np.array([9.0, 19.0])
solution = np.linalg.solve(A, b)
print('solution to Ax=b:', solution)
print('check:', A @ solution)

solution to Ax=b: [1.6 5.8]
check: [ 9. 19.]


Solving Ax = b matters because many estimation and fitting problems reduce to finding parameters that satisfy or approximately satisfy such systems.

In [3]:
X = np.array([[1, 2], [3, 4], [5, 6]])
print('rows as observations:\n', X)
print('column means:', X.mean(axis=0))
print('transpose:\n', X.T)

rows as observations:
 [[1 2]
 [3 4]
 [5 6]]
column means: [3. 4.]
transpose:
 [[1 3 5]
 [2 4 6]]


In data science and ML, a matrix often means rows are examples and columns are features. That interpretation lets you express preprocessing and model calculations cleanly.

In [4]:
rotation_like = np.array([[0, -1], [1, 0]])
v = np.array([2.0, 1.0])
print('transformed vector:', rotation_like @ v)

transformed vector: [-1.  2.]


Thinking of matrices as transformations is especially helpful for neural networks and dimensionality-reduction methods, where learned parameter matrices reshape data into new spaces.

## Final Takeaway
Matrices are the workhorses of ML because they can represent both data and transformations. Matrix multiplication, transposes, and linear systems are not separate mechanical skills; they are pieces of one representation-and-transformation story.