# NumPy Broadcasting, Indexing, and Linear Algebra Flow
Many array bugs do not come from arithmetic itself. They come from shape mismatches, indexing assumptions, and forgetting what the operation means geometrically. This notebook stays close to those pressure points so matrix work feels less fragile.

Indexing in NumPy is really about choosing which coordinates survive and how the resulting array views or copies the original memory. Once shapes are kept visible in your head, a lot of confusion disappears.

In [1]:
import numpy as np

x = np.arange(1, 13).reshape(3, 4)
print(x)
print('row 1:', x[1])
print('column 2:', x[:, 2])
print('last row, last two columns:', x[-1, -2:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
row 1: [5 6 7 8]
column 2: [ 3  7 11]
last row, last two columns: [11 12]


Basic slicing usually returns a view. Advanced indexing often returns a copy. This distinction matters because it changes whether future mutation reaches the original array.

In [2]:
basic = x[:, 1:3]
advanced = x[:, [1, 3]]
basic[0, 0] = 777
advanced[0, 0] = -1
print('x after basic slice mutation:\n', x)
print('advanced indexing result:\n', advanced)
print('shares memory basic:', np.shares_memory(x, basic))
print('shares memory advanced:', np.shares_memory(x, advanced))

x after basic slice mutation:
 [[  1 777   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
advanced indexing result:
 [[-1  4]
 [ 6  8]
 [10 12]]
shares memory basic: True
shares memory advanced: False


Broadcasting becomes especially useful when you stop reading it as a trick and start reading it as a shape negotiation. NumPy lines up dimensions from the right and checks whether dimensions are equal or one of them is 1.

In [3]:
a = np.arange(6).reshape(2, 3)
b = np.array([100, 200, 300])
print('a:\n', a)
print('b:', b)
print('a + b:\n', a + b)

a:
 [[0 1 2]
 [3 4 5]]
b: [100 200 300]
a + b:
 [[100 201 302]
 [103 204 305]]


Linear algebra operations deserve careful reading because * means elementwise multiplication while @ means matrix multiplication. That one character difference carries a major semantic difference.

In [4]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])
print('elementwise:\n', m1 * m2)
print('matrix product:\n', m1 @ m2)
print('transpose of m1:\n', m1.T)

elementwise:
 [[ 5 12]
 [21 32]]
matrix product:
 [[19 22]
 [43 50]]
transpose of m1:
 [[1 3]
 [2 4]]


At the conceptual level, matrix multiplication combines rows with columns. At the runtime level, NumPy checks dimensional compatibility and then dispatches to optimized numerical routines. Interviewers often care whether you can explain both views.

In [5]:
v = np.array([3.0, 4.0])
print('norm:', np.linalg.norm(v))
print('unit vector:', v / np.linalg.norm(v))

A = np.array([[2.0, 1.0], [1.0, 3.0]])
b = np.array([1.0, 2.0])
solution = np.linalg.solve(A, b)
print('solution:', solution)
print('check:', A @ solution)

norm: 5.0
unit vector: [0.6 0.8]
solution: [0.2 0.6]
check: [1. 2.]


Solving Ax = b directly communicates one of the most important math-to-code bridges in ML. Data may be stored as arrays, transformations may be written as matrix operations, and numerical routines exist to solve the underlying systems without manually coding elimination step by step.

In [6]:
u = np.array([1.0, 2.0, 3.0])
v = np.array([4.0, 5.0, 6.0])
print('dot product:', u @ v)
print('outer product:\n', np.outer(u, v))

dot product: 32.0
outer product:
 [[ 4.  5.  6.]
 [ 8. 10. 12.]
 [12. 15. 18.]]


A useful study habit is to keep asking what shape an expression will return before running it. That simple discipline prevents a surprising amount of real-world debugging pain.

## Final Takeaway
Most productive NumPy work comes down to shape awareness, view-versus-copy awareness, and understanding the semantic difference between elementwise operations and linear-algebra operations. If you keep those three ideas active, the library becomes far less error-prone.